name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Configure secrets
      run: |
        dotnet user-secrets init --project Test/Test.Postmates.NET/Test.Postmates.NET.csproj \
        && dotnet user-secrets set "Postmates.ServiceApiKey" ${{ secrets.SANDBOX_KEY }} --project Test/Test.Postmates.NET/Test.Postmates.NET.csproj \
        && dotnet user-secrets set "Postmates.CustomerId" ${{ secrets.CUSTOMER_ID }} --project Test/Test.Postmates.NET/Test.Postmates.NET.csproj
    - name: run tests
      run: dotnet test Test/Test.Postmates.NET/Test.Postmates.NET.csproj
